In [2]:
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from autots import AutoTS
import pathlib

In [3]:
well_data = pd.read_excel('../data/Data-Wells.xlsx')
s =  well_data['Well Name'] == '110 Parkland Plaza'

KeyboardInterrupt:

In [ ]:
res = well_data[s]
res

In [ ]:
res.to_excel("./110_Parkland_Plaza.xlsx")

In [16]:
rr = pd.read_excel("./110_Parkland_Plaza.xlsx")
rr

,Unnamed: 0,Sample ID,Well Name,Entered,"1,4-Dioxane Results (ppb)",Date Sampled,Time Sampled,Date Received,Date Analyzed,Reporting Limit,...,Well Comments,Scr Elev Range,bar color,BegFolder KML,EndFolder KML,BegFolder2KML,EndFolder2KML,Max-to-date.1,MaxToDateFlag,Last Date Rd
0,16,57,110 Parkland Plaza,NaN,17.0,08/22/86,NaN,NaN,NaN,1,...,NaN,840-860,orange,<Folder><name>110 Parkland Plaza</name>,NaN,<Folder><name>840-860</name>,NaN,17.0,MaxToDate,2019-09-12
1,17,58,110 Parkland Plaza,NaN,17.0,09/19/86,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,17.0,MaxToDate,2019-09-12
2,18,61,110 Parkland Plaza,NaN,12.0,10/10/86,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,17.0,NaN,2019-09-12
3,19,62,110 Parkland Plaza,NaN,1.0,10/10/86,NaN,NaN,NaN,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,17.0,NaN,2019-09-12
4,20,187,110 Parkland Plaza,NaN,7.0,11/09/87,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,17.0,NaN,2019-09-12
5,21,188,110 Parkland Plaza,NaN,18.0,11/09/87,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,MaxToDate,2019-09-12
6,22,249,110 Parkland Plaza,NaN,13.0,04/18/88,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
7,23,301,110 Parkland Plaza,NaN,14.0,12/09/88,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
8,24,402,110 Parkland Plaza,NaN,11.0,07/19/89,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
9,25,496,110 Parkland Plaza,NaN,12.0,01/30/90,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
10,26,618,110 Parkland Plaza,NaN,8.0,08/01/90,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
11,27,716,110 Parkland Plaza,NaN,10.0,01/23/91,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
12,28,774,110 Parkland Plaza,NaN,10.0,08/22/91,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
13,29,901,110 Parkland Plaza,NaN,8.0,07/23/92,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
14,30,970,110 Parkland Plaza,NaN,9.0,03/03/93,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
15,31,1082,110 Parkland Plaza,NaN,9.0,08/23/93,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
16,32,3221,110 Parkland Plaza,NaN,3.0,12/21/98,NaN,NaN,NaN,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
17,33,4011,110 Parkland Plaza,NaN,2.0,08/19/99,NaN,NaN,NaN,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
18,34,4326,110 Parkland Plaza,NaN,5.0,11/12/99,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
19,35,4648,110 Parkland Plaza,NaN,8.0,02/15/00,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
20,36,5398,110 Parkland Plaza,NaN,7.0,08/16/00,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
21,37,6756,110 Parkland Plaza,NaN,6.0,01/29/01,13:40,01/29/01,02/05/01,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
22,38,7595,110 Parkland Plaza,NaN,5.0,05/10/01,10:58,05/10/01,05/14/01,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
23,39,8300,110 Parkland Plaza,NaN,9.0,07/24/01,12:58,07/24/01,07/25/01,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
24,40,9288,110 Parkland Plaza,NaN,9.0,11/03/01,13:38,11/03/01,11/12/01,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
25,41,9785,110 Parkland Plaza,NaN,5.0,01/10/02,14:12,01/10/02,01/10/02,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
26,42,10665,110 Parkland Plaza,NaN,6.0,04/18/02,9:12,04/18/02,05/05/02,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
27,43,11713,110 Parkland Plaza,NaN,10.0,07/28/02,15:55,07/28/02,08/21/02,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
28,44,12691,110 Parkland Plaza,NaN,8.0,11/03/02,13:06,11/04/02,11/04/02,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
29,45,13317,110 Parkland Plaza,NaN,9.0,01/28/03,11:09,01/28/03,01/31/03,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
30,46,14146,110 Parkland Plaza,NaN,7.0,05/01/03,11:48,05/01/03,05/08/03,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
31,47,14733,110 Parkland Plaza,07/09/03,8.0,07/09/03,9:10,07/09/03,07/09/03,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,8.0,MaxToDate,2019-09-12
32,48,15207,110 Parkland Plaza,10/06/03,8.0,10/03/03,11:00,10/03/03,10/06/03,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,8.0,MaxToDate,2019-09-12
33,49,15783,110 Parkland Plaza,02/04/04,8.0,02/02/04,12:42,02/02/04,02/05/04,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,8.0,MaxToDate,2019-09-12
34,50,16749,110 Parkland Plaza,04/28/04,7.0,04/27/04,9:31,04/28/04,05/12/04,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,7.0,MaxToDate,2019-09-12
35,51,17473,110 Parkland Plaza,10/12/04,7.0,10/11/04,15:15,10/11/04,10/18/04,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,7.0,MaxToDate,2019-09-12
36,52,18372,110 Parkland Plaza,05/04/05,5.0,05/02/05,14:13,05/02/05,05/20/05,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,5.0,MaxToDate,2019-09-12
37,53,19440,110 Parkland Plaza,11/11/05,5.0,11/09/05,10:14,11/09/05,11/10/05,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,5.0,MaxToDate,2019-09-12
38,54,20506,110 Parkland Plaza,05/08/06,6.0,05/03/06,15:00,05/03/06,05/08/06,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,6.0,MaxToDate,2019-09-12
39,55,21667,110 Parkland Plaza,10/12/06,5.0,10/11/06,8:50,10/11/06,10/12/06,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,5.0,MaxToDate,2019-09-12
40,56,25813,110 Parkland Plaza,05/22/07,5.0,05/21/07,8:55,05/21/07,05/22/07,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,5.0,MaxToDate,2019-09-12
41,57,27769,110 Parkland Plaza,10/12/07,6.0,10/11/07,9:50,10/11/07,10/12/07,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,6.0,MaxToDate,2019-09-12
42,58,29693,110 Parkland Plaza,07/29/08,5.0,07/29/08,13:40,07/29/08,07/30/08,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,5.0,MaxToDate,2019-09-12
43,59,32528,110 Parkland Plaza,08/13/09,4.0,08/10/09,10:05,08/10/09,08/10/09,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,4.0,MaxToDate,2019-09-12
44,60,34454,110 Parkland Plaza,07/29/10,4.0,07/29/10,7:50,07/29/10,07/30/10,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,4.0,MaxToDate,2019-09-12
45,61,38381,110 Parkland Plaza,09/17/11,3.0,09/17/11,14:00,NaN,09/19/11,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,3.0,MaxToDate,2019-09-12
46,62,39041,110 Parkland Plaza,08/14/12,3.0,08/14/12,13:55,NaN,09/19/12,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,3.0,MaxToDate,2019-09-12
47,63,61062,110 Parkland Plaza,07/18/13,5.0,07/18/13,14:25,NaN,07/22/13,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,5.0,MaxToDate,2019-09-12
48,64,64611,110 Parkland Plaza,08/01/14,2.0,08/01/14,14:16,NaN,08/05/14,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,2.0,MaxToDate,2019-09-12
49,65,66944,110 Parkland Plaza,07/30/15,2.0,07/30/15,15:46,NaN,08/01/15,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,2.0,MaxToDate,2019-09-12
50,66,70464,110 Parkland Plaza,09/07/16,2.5,09/07/16,13:00,NaN,09/13/16,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,2.5,MaxToDate,2019-09-12
51,67,72102,110 Parkland Plaza,07/26/17,1.6,07/26/17,10:40,NaN,07/28/17,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,1.6,MaxToDate,2019-09-12
52,68,74455,110 Parkland Plaza,08/14/18,1.4,08/14/18,11:38,NaN,08/17/18,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,1.4,MaxToDate,2019-09-12
53,69,77470,110 Parkland Plaza,09/12/19,1.2,09/12/19,9:12,NaN,09/20/19,1,...,NaN,840-860,yellow,NaN,</Folder>,NaN,</Folder>,1.2,MaxToDate,2019-09-12

In [23]:
start_year = 20
start_dio  = 20
fake = pd.DataFrame(columns=rr.columns)

list = []
for index, row in rr.iterrows():
    row['Date Sampled'] = "01/01/" + str(start_year)
    row['1,4-Dioxane Results (ppb)'] = start_dio
    print(type(row))
    fake.append(row, ignore_index=True)
    list.append(row)
    start_year = start_year + 1
    start_dio = start_dio + 5

fake

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

Empty DataFrame
Columns: [Unnamed: 0, Sample ID, Well Name, Entered, 1,4-Dioxane Results (ppb), Date Sampled, Time Sampled, Date Received, Date Analyzed, Reporting Limit, Reporting Lab, Static Reading, Static Time, Static Only?, Qualifier(s), Comments, Bromate Results (ppb), Date Bromate Analyzed, Bromate Reporting Limit, Bromate Reporting Lab, Bromide Results (ppb), Date Bromide Analyzed, Bromide Reporting Limit, Bromide Reporting Lab, Completed Sample?, DateRead#, dioxane holding time, count days>14, year sampled, month sampled, yyyy-mm-dd, next date, ppb as #, adj ppb as text, WellName/Year, Max/Yr, Max-to-date, MaxFlag/Yr, MaxPPB, MaxFlag, Date of Max, Aquifer, AQUIFER2, Map Location, X CORD, Y CORD, LONG, LAT, Date Installed, Well Driller (if known), Well Types, Sampling Interval, Static Interval, Boring Depth  (Feet bgl), Ground Elevation, TOC Elevation AMSL (Feet), Depth from TOC to bottom of screen (Feet), TOC above Ground,  Approx  Elev = Ground - Bottom Scr, Official Elev = TOC - TOC to Scr Bot elev, Genl Bot Scr Elev, Top of Screen 1, Bottom of Screen 1, Screen Length (Feet), Top of Screen 2, Bottom of Screen 2, Well Comments, Scr Elev Range, bar color, BegFolder KML, EndFolder KML, BegFolder2KML, EndFolder2KML, Max-to-date.1, MaxToDateFlag, Last Date Rd]
Index: []

[0 rows x 76 columns]

In [26]:
list
df=pd.DataFrame(list[0:10],columns=rr.columns)
df

,Unnamed: 0,Sample ID,Well Name,Entered,"1,4-Dioxane Results (ppb)",Date Sampled,Time Sampled,Date Received,Date Analyzed,Reporting Limit,...,Well Comments,Scr Elev Range,bar color,BegFolder KML,EndFolder KML,BegFolder2KML,EndFolder2KML,Max-to-date.1,MaxToDateFlag,Last Date Rd
0,16,57,110 Parkland Plaza,NaN,20,01/01/20,NaN,NaN,NaN,1,...,NaN,840-860,orange,<Folder><name>110 Parkland Plaza</name>,NaN,<Folder><name>840-860</name>,NaN,17.0,MaxToDate,2019-09-12
1,17,58,110 Parkland Plaza,NaN,25,01/01/21,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,17.0,MaxToDate,2019-09-12
2,18,61,110 Parkland Plaza,NaN,30,01/01/22,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,17.0,NaN,2019-09-12
3,19,62,110 Parkland Plaza,NaN,35,01/01/23,NaN,NaN,NaN,1,...,NaN,840-860,yellow,NaN,NaN,NaN,NaN,17.0,NaN,2019-09-12
4,20,187,110 Parkland Plaza,NaN,40,01/01/24,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,17.0,NaN,2019-09-12
5,21,188,110 Parkland Plaza,NaN,45,01/01/25,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,MaxToDate,2019-09-12
6,22,249,110 Parkland Plaza,NaN,50,01/01/26,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
7,23,301,110 Parkland Plaza,NaN,55,01/01/27,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
8,24,402,110 Parkland Plaza,NaN,60,01/01/28,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12
9,25,496,110 Parkland Plaza,NaN,65,01/01/29,NaN,NaN,NaN,1,...,NaN,840-860,orange,NaN,NaN,NaN,NaN,18.0,NaN,2019-09-12

In [27]:

df.to_excel("./110_Parkland_Plaza_predict.xlsx")